### PR TITLE
add controller logging format to managed controllers

### PR DESCRIPTION
**Pull request by OliverMKing**
# Description

We have two kinds of controllers in app routing. For controllers that are created completely through controller manager they have an internal logging format where they add a few additional fields. We need to add our controller fields to this logger when creating these controllers or else they will be missing fields we want on all controller logs.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested manually and with e2e and unit

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by davidgamero — APPROVED** [review]
lgtm

**Review by bfoley13 — APPROVED** [review]
Looks good! Will be nice to have this roll out for updated logging

**Review by gambtho — APPROVED** [review]

**Pull request merged**
