### PR TITLE
Add CHANGELOG and update release workflow

### PR DESCRIPTION
**Pull request by OliverMKing**
# Description

Adds a CHANGELOG to our release process. Also automates creating a GitHub release when pushing an image.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested on a separate repo. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jaiveerk — APPROVED** [review]

**Review by hsubramanianaks — APPROVED** [review]
looks good to me. Only suggestion would be to make sure this works fine you could do a fake release in your forked repo and show it here that this workflow works fine.

**Comment by OliverMKing** [comment]
> looks good to me. Only suggestion would be to make sure this works fine you could do a fake release in your forked repo and show it here that this workflow works fine.

Good suggestion! https://github.com/aksatlanta-testing/anotherolivertest/actions/runs/5468686657/jobs/9956650171

Here's the runs from yesterday.

**Pull request merged**
